name: azure publish

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: blog-post
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          # extended: true

      - name: Build
        run: hugo -D

      #deploy to azure
      - name: Deploy
        uses: tibor19/static-website-deploy@v1
        with:
          enabled-static-website: 'true'
          connection-string: ${{ secrets.CONNECTION_STRING }}
          folder: blog-post/public

